spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clinicamedica_api
    username: root
    password: root1@
  jpa:
    show-sql: true
    properties:
      hibernate:
       format_sql: true   
    
